name: FrozedDisguise
version: 1.8
main: club.frozed.frozeddisguise.FrozedDisguise
authors:
  - Elb1to
  - FrozedClubDevelopment
depend:
  - ProtocolLib
  - NickAPI
commands:
  disguise:
    aliases: [dis, d]
  undisguise:
    aliases: [undis, ud]
  disguiselist:
    aliases: [dislist, dlist]
  checkuuid:
    aliases: [uuidcheck]
  disguisehelp:
    aliases: [dishelp, dhelp]
  disguiserank:
    aliases: [disrank, drank, dr]
  undisguiserank:
    aliases: [undisrank, udrank, udr]
  frozeddisguise:
    aliases: [fd, frozeddis, frozedclub]