name: FrozedDisguise
version: 1.0
main: club.frozed.frozeddisguise.FrozedDisguise
authors:
  - Elb1to
  - Scalebound
  - FrozedDevelopment
depend:
  - ProtocolLib
  - NickAPI
commands:
  disguise:
    aliases: [dis, d]
  undisguise:
    aliases: [undis, ud]
  disguiselist:
    aliases: [dislist]
  checkuuid:
    aliases: [uuidcheck]